name: Pull request checker
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      VALID_SECTIONS:
        required: true
        type: string

jobs:
  checker:
    runs-on: ubuntu-latest
    name: Pull request check
    env:
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check source branch name
        id: validate-name
        run: |
          echo $BRANCH_NAME
          if [[ ! $BRANCH_NAME =~ ^wip/ | ! $BRANCH_NAME =~ ^dev/ ]]; then
            if [[ $BRANCH_NAME == release ]]; then
              exit 0
            fi
            if [[ $BRANCH_NAME =~ ^feature/ ]]; then
              exit 0
            fi
            if [[ $BRANCH_NAME == main ]]; then
              exit 0
            fi
            echo "Error: Branch name must start with 'wip/' or 'dev/' prefix."
            exit 1
          fi

          CENTRAL_SECTION=$(echo $BRANCH_NAME | cut -d'/' -f2)
          VALID_SECTIONS=${{ inputs.VALID_SECTIONS }}

          IFS=',' read -r -a sections_array <<< "$VALID_SECTIONS"

          if [[ ! " ${sections_array[@]} " =~ " ${CENTRAL_SECTION} " ]]; then
            echo "Error: Central section '$CENTRAL_SECTION' is not valid."
            exit 1
          fi
          
